server:
  port: 8001
  context-path: /user
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admine
    url: jdbc:mysql://localhost:3306/spring_cloud_first?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false

## mybatis 配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.lwf.first.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level: debug
eureka:
  client:                                                   #客户端注册进eureka服务列表内
    service-url:
      #单机defaultZone: http://localhost:7002/eureka
      defaultZone: http://localhost:8008/eureka/
      #集群是
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: user8001
    prefer-ip-address: true                                  #访问路径可以显示IP地址

info:                                                         #在Eure页面访问info返回的信息的配置
  app.name: my spring cloud
  company.name: www.lwf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$